-- Drop all procedures
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.COUNT_PDF_PAGES_PROC();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.HANDLE_PDF_FILES();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MANAGE_MANUAL_REVIEW_FILES();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_MODEL_FLATTEN();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.LOAD_MODEL_VALIDATED();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MOVEFILES_TO_SOURCE();
DROP PROCEDURE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.IGNOREFILES_TO_STAGE();

-- Drop all tasks
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.PREPROCESSING;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.EXTRACT_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MANUAL_CHECKUP_FILES;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.FLATTEN_DATA;
DROP TASK IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.VALIDATE_DATA;

-- Drop any additional objects referenced in the script
-- Note: Ensure these objects exist before attempting to drop them
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.MODEL_METADATA;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.SCORE_THRESHOLD;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.order_col_score_failed_history;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.delivery_col_score_failed_history;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.manual_review_history_log;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.DOCAI_PREFILTER;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.DOCAI_ORDERFORM_EXTRACTION;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Order_Flatten;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Delivery_Flatten;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Order_Validated;
DROP TABLE IF EXISTS DS_DEV_DB.DOC_AI_SCHEMA.Delivery_Validated;

-- Additional cleanup for stages if needed
REMOVE @DOC_STAGE;
REMOVE @IGNOIRED_DOCS;
REMOVE @MANUAL_REVIEW;